# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9bca2fee8cb2773b727afa7c0a6d08cbedce7aa3ecd58b8a5101e08a73dc389e2b34eaa191452c7466a5e8a70f364af316bc6f5db9eea16f017774208b9d4f90

test:
  secret_key_base: 8f067090990c1d39cdacfc15bdcf98875da9db3dead60a7888f76cc6f85593219d015d2be70f68d051f89076731b4ffb003b1c8d58de1e6bd127c841c8f02ebf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
